tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "awscli"
brew "bash"
brew "bat"
brew "chruby"
brew "curl"
brew "fish"
brew "exa"
brew "git"
brew "jenv"
brew "jq"
brew "ncdu"
brew "neovim"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-install"
brew "the_silver_searcher"
brew "wget"
brew "zsh"

cask "font-hack-nerd-font"
cask "iterm2"
cask "temurin8"
cask "temurin11"
cask "visual-studio-code"
