#!/bin/sh

# Welcome to ToppleTheNun's variant of the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  fancy_echo "Changing your shell to zsh..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    /bin/bash -c \
      "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old homebrew-cask..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "antigen"
brew "aws-nuke"
brew "awscli"
brew "bash"
brew "bat"
brew "chruby"
brew "coreutils"
brew "csvq"
brew "curl"
brew "deno"
brew "dog"
brew "dust"
brew "exa"
brew "fd"
brew "fish"
brew "flyctl"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "go"
brew "grc"
brew "helm"
brew "htop"
brew "httpie"
brew "jenv"
brew "jq"
brew "k6"
brew "k9s"
brew "ktlint"
brew "kubeseal"
brew "kubespy"
brew "kustomize"
brew "libyaml"
brew "maven"
brew "ncdu"
brew "neovim"
brew "openssl@3"
brew "pipx"
brew "postgresql@14"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.9"
brew "rcm"
brew "rename"
brew "ripgrep"
brew "ruby-install"
brew "starship"
brew "the_silver_searcher"
brew "tilt"
brew "wget"
brew "zoxide"
brew "zsh"
cask "docker"
cask "font-hack-nerd-font"
cask "iterm2"
cask "temurin11"
cask "temurin17"
cask "temurin8"
cask "visual-studio-code"
cask "wombat"
EOF

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

fancy_echo "Done!"
